"""
Google Gemini provider implementation.
"""
import asyncio
import logging
from typing import Optional
from .base import BaseLLMProvider

logger = logging.getLogger(__name__)


class GeminiProvider(BaseLLMProvider):

    provider_name = "gemini"

    def __init__(self, api_key: str):
        import google.generativeai as genai
        genai.configure(api_key=api_key, transport="rest")
        self._genai = genai

    async def complete(
        self,
        prompt: str,
        model: str = "gemini-2.0-flash",
        temperature: float = 0.7,
        max_tokens: int = 1024,
        system: Optional[str] = None,
    ) -> str:
        full_prompt = f"{system}\n\n{prompt}" if system else prompt

        # Determine target model name
        target_model = model
        if target_model in ["gemini-3-flash-preview", "gemini-1.5-flash"]:
            target_model = "gemini-2.0-flash"

        try:
            gen_model = self._genai.GenerativeModel(target_model)
        except Exception:
            gen_model = self._genai.GenerativeModel("gemini-2.0-flash")

        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = asyncio.get_event_loop()

        def _generate():
            try:
                return gen_model.generate_content(
                    full_prompt,
                    generation_config=self._genai.types.GenerationConfig(
                        temperature=temperature,
                        max_output_tokens=max_tokens,
                    ),
                )
            except Exception as e:
                # If first model fails, attempt fallback
                logger.warning("Primary Gemini model %s failed: %s. Trying fallback gemini-2.0-flash...", target_model, e)
                fb_model = self._genai.GenerativeModel("gemini-2.0-flash")
                return fb_model.generate_content(
                    full_prompt,
                    generation_config=self._genai.types.GenerationConfig(
                        temperature=temperature,
                        max_output_tokens=max_tokens,
                    ),
                )

        response = await loop.run_in_executor(None, _generate)

        try:
            return response.text or ""
        except Exception:
            if hasattr(response, "candidates") and response.candidates:
                parts = response.candidates[0].content.parts
                return "".join(p.text for p in parts if hasattr(p, "text")) or ""
            return "No text response generated by Gemini."

    def get_available_models(self) -> list[dict]:
        return [
            {
                "provider": "gemini",
                "model": "gemini-2.0-flash",
                "display_name": "Gemini 2.0 Flash",
                "description": "Fast multimodal Gemini model with high quality.",
                "max_tokens": 8192,
            },
        ]

